const fs = require('fs'), vm = require('vm'), assert = require('assert');
globalThis.crypto = require('crypto').webcrypto;
globalThis.SDCompanion = {};
for (const f of ['src/shared/constants.js', 'src/shared/utils.js', 'src/shared/schedule.js', 'src/shared/condition-registry.js', 'src/shared/rule-query.js', 'src/shared/defaults.js']) vm.runInThisContext(fs.readFileSync(f, 'utf8'), { filename: f });
const SD = SDCompanion;
assert.equal(SD.Constants.BUILD_VERSION, '2.1.1');
const state = SD.Defaults.state(), p = SD.Defaults.profile(), r = SD.Defaults.rule('R');
assert('safety' in state.system);
assert(!('dryRun' in state.system));
assert.deepEqual(p.schedules, []);
assert.deepEqual(p.rules, []);
assert(!('safety' in r));
assert.equal(r.schedule.mode, 'always');
assert.deepEqual(r.actions, []);
assert('executionPolicy' in r);
assert('conflict' in r);
assert('randomDelay' in r);
assert.equal(SD.Schedule.matchesAny([], [], new Date()), false);
assert.equal(SD.Defaults.action('comment').templates.length, 0);
const manifest = JSON.parse(fs.readFileSync('manifest.json'));
assert.equal(manifest.version, '2.1.1');
assert(!manifest.content_scripts);
assert(manifest.permissions.includes('unlimitedStorage'));
console.log('redesign-test: OK');
