(() => {
  const root = globalThis.SDCompanion = globalThis.SDCompanion || {};
  root.Constants = Object.freeze({
    APP_NAME: "SD Companion",
    DISPLAY_VERSION: "V2",
    BUILD_VERSION: "2.2.1",
    SCHEMA_VERSION: 33,
    STORAGE_KEYS: Object.freeze({
      STATE: "sdCompanionState",
      LOGS: "sdCompanionLogs",
      AUDIT: "sdCompanionAudit",
      LEDGER: "sdCompanionLedger",
      JOBS: "sdCompanionJobs",
      CURSORS: "sdCompanionCursors",
      LOCAL_CREDENTIALS: "sdCompanionLocalCredentials",
      SESSION_CREDENTIALS: "sdCompanionSessionCredentials",
      INSTALL: "sdCompanionInstallMarker",
      SECURITY: "sdCompanionSecurity",
      SECURITY_SESSION: "sdCompanionSecuritySession",
      SECURITY_RISK_TOKENS: "sdCompanionSecurityRiskTokens"
    }),
    ALARMS: Object.freeze({ MONITOR: "sd-rest-monitor", HEALTH: "sd-rest-health", ALARM_STOP: "sd-active-alarm-stop", METADATA_SYNC: "sd-metadata-sync" }),
    MESSAGE: Object.freeze({
      GET_STATE: "GET_STATE",
      SAVE_STATE: "SAVE_STATE",
      SET_MONITORING: "SET_MONITORING",
      UPDATE_APPEARANCE: "UPDATE_APPEARANCE",
      UPDATE_SYSTEM: "UPDATE_SYSTEM",
      SAVE_SETTINGS: "SAVE_SETTINGS",
      GET_LOGS: "GET_LOGS",
      CLEAR_LOGS: "CLEAR_LOGS",
      EXPORT_LOGS: "EXPORT_LOGS",
      GET_AUDIT: "GET_AUDIT",
      CLEAR_AUDIT: "CLEAR_AUDIT",
      ADD_SERVER: "ADD_SERVER",
      UPDATE_SERVER: "UPDATE_SERVER",
      DELETE_SITE: "DELETE_SITE",
      SET_ACTIVE_SITE: "SET_ACTIVE_SITE",
      SET_ACTIVE_PROFILE: "SET_ACTIVE_PROFILE",
      SAVE_CREDENTIAL: "SAVE_CREDENTIAL",
      DELETE_CREDENTIAL: "DELETE_CREDENTIAL",
      TEST_CONNECTION: "TEST_CONNECTION",
      DISCOVER_PROJECTS: "DISCOVER_PROJECTS",
      SYNC_SITE: "SYNC_SITE",
      REFRESH_HEALTH: "REFRESH_HEALTH",
      RUN_CYCLE: "RUN_CYCLE",
      GET_JOBS: "GET_JOBS",
      CANCEL_JOB: "CANCEL_JOB",
      CANCEL_JOBS: "CANCEL_JOBS",
      PROCESS_JOB: "PROCESS_JOB",
      PROCESS_JOBS: "PROCESS_JOBS",
      APPROVE_JOB: "APPROVE_JOB",
      APPROVE_JOBS: "APPROVE_JOBS",
      PREVIEW_BULK_OPERATION: "PREVIEW_BULK_OPERATION",
      RUN_BULK_OPERATION: "RUN_BULK_OPERATION",
      CANCEL_OPERATION: "CANCEL_OPERATION",
      SET_OPEN_TARGET: "SET_OPEN_TARGET",
      PLAY_ALARM: "PLAY_ALARM",
      STOP_ALARM: "STOP_ALARM",
      REFRESH_TAB_STATUS: "REFRESH_TAB_STATUS",
      GET_ALARM_STATE: "GET_ALARM_STATE",
      DELETE_PROFILE: "DELETE_PROFILE",
      CLEAR_CACHE: "CLEAR_CACHE",
      CLEAR_PROFILE_DATA: "CLEAR_PROFILE_DATA",
      FACTORY_RESET: "FACTORY_RESET",
      GET_RULE_PREVIEW: "GET_RULE_PREVIEW",
      REFRESH_CURRENT_MATCHES: "REFRESH_CURRENT_MATCHES",
      LOG_UI_EVENT: "LOG_UI_EVENT",
      GET_SECURITY_STATUS: "GET_SECURITY_STATUS",
      VERIFY_SECURITY: "VERIFY_SECURITY",
      SET_SECURITY_PASSCODE: "SET_SECURITY_PASSCODE",
      UPDATE_SECURITY_SETTINGS: "UPDATE_SECURITY_SETTINGS",
      DISABLE_SECURITY: "DISABLE_SECURITY",
      LOCK_EXTENSION: "LOCK_EXTENSION"
    }),
    LEVEL: Object.freeze({ DEBUG: "debug", INFO: "info", WARN: "warn", ERROR: "error", SUCCESS: "success" }),
    LOG_LEVELS: Object.freeze(["debug", "info", "warn", "error"]),
    ACTION: Object.freeze({ ASSIGN: "assign", COMMENT: "comment", TRANSITION: "transition", EDIT_FIELDS: "edit-fields", LABELS: "labels", PRIORITY: "priority", ALARM: "alarm", NOTIFICATION: "notification" }),
    ASSIGN_MODE: Object.freeze({ ME: "me", SPECIFIC: "specific", RANDOM: "random", UNASSIGN: "unassign" }),
    TRANSITION_METHOD: Object.freeze({ WORKFLOW_DESIGNER: "workflow-designer", ISSUE_EXTRACTION: "issue-extraction", TARGET_STATUS_RANDOM: "target-status-random", MANUAL_NAME: "manual-name" }),
    THEME: Object.freeze({ EMERALD: "emerald-glass", MIDNIGHT: "midnight-glass", GRAPHITE: "graphite-glass", VIOLET: "violet-glass", AMBER: "amber-glass", CRIMSON: "crimson-glass", OCEAN: "ocean-glass", COPPER: "copper-glass" }),
    OPEN_TARGET: Object.freeze({ POPUP: "popup", SIDEPANEL: "sidepanel" }),
    API: Object.freeze({ VERSION: "2", PAGE_SIZE: 100, MAX_ISSUES: 1000, MAX_FILTERS: 5000, MAX_USERS: 20000, REQUEST_TIMEOUT_MS: 30000, MAX_RETRIES: 5, MAX_PROJECTS: 2500, MAX_TRANSITION_SAMPLES: 2000 }),
    LIMITS: Object.freeze({
      POLL_MIN_SECONDS: 30,
      POLL_MAX_SECONDS: 86400,
      POLL_JITTER_MAX: 50,
      REQUEST_SPACING_MIN_MS: 100,
      REQUEST_SPACING_MAX_MS: 10000,
      REQUEST_JITTER_MAX: 50,
      REQUEST_TIMEOUT_MIN_MS: 3000,
      REQUEST_TIMEOUT_MAX_MS: 120000,
      REQUEST_RETRIES_MAX: 5,
      REQUESTS_PER_MINUTE_MIN: 10,
      REQUESTS_PER_MINUTE_MAX: 600,
      CONCURRENCY_MIN: 1,
      CONCURRENCY_MAX: 4,
      HEALTH_MINUTES_MIN: 1,
      HEALTH_MINUTES_MAX: 120,
      HEALTH_MIN_SECONDS: 60,
      HEALTH_MAX_SECONDS: 7200,
      BACKOFF_MIN_SECONDS: 5,
      BACKOFF_MAX_SECONDS: 300,
      TRANSITION_SAMPLES_PER_CONTEXT_MAX: 5,
      ACTION_DELAY_MAX_SECONDS: 86400,
      RULE_MAX_ISSUES: 500,
      RULE_MAX_ACTIONS: 1000,
      RULE_MAX_HOURLY: 1000,
      CUSTOM_SOUND_MAX_BYTES: 2 * 1024 * 1024,
      AUDIT_MAX: 3000,
      LOG_MAX: 3000,
      JOBS_MAX: 1500,
      LEDGER_MAX: 10000,
      CURSOR_OVERLAP_MIN_SECONDS: 30,
      CURSOR_OVERLAP_MAX_SECONDS: 7200,
      REPEAT_SECONDS_MIN: 30,
      REPEAT_SECONDS_MAX: 604800,
      METADATA_SYNC_MIN_SECONDS: 300,
      METADATA_SYNC_MAX_SECONDS: 604800,
      RULE_ACTION_COUNT_MAX: 50,
      COMMENT_TEMPLATE_COUNT_MAX: 100,
      COMMENT_TEMPLATE_MAX_CHARS: 30000,
      JQL_MAX_CHARS: 20000,
      PROFILE_IMPORT_MAX_BYTES: 10 * 1024 * 1024,
      ACTIVITY_REFRESH_MIN_SECONDS: 3,
      ACTIVITY_REFRESH_MAX_SECONDS: 300,
      CONNECTION_LOSS_MIN_SECONDS: 60,
      CONNECTION_LOSS_MAX_SECONDS: 86400,
      CONNECTION_LOSS_FAILURES_MIN: 1,
      CONNECTION_LOSS_FAILURES_MAX: 500,
      SECURITY_SESSION_MINUTES_MIN: 1,
      SECURITY_SESSION_MINUTES_MAX: 10080,
      SECURITY_PASSWORD_MAX_CHARS: 128,
      ALERT_THROTTLE_MAX_ALERTS: 100,
      ALERT_THROTTLE_WINDOW_MAX_MINUTES: 1440
    }),
    JOB: Object.freeze({ AWAITING_APPROVAL: "awaiting-approval", PENDING: "pending", RUNNING: "running", SUCCEEDED: "succeeded", FAILED: "failed", CANCELLED: "cancelled", SKIPPED: "skipped" }),
    EXECUTION_POLICY: Object.freeze({ ONCE_ISSUE: "once-per-issue", ONCE_STATUS: "once-per-status", ONCE_UPDATE: "once-per-update", REPEAT: "repeat-after" }),
    CONFLICT_MODE: Object.freeze({ CONTINUE: "continue", STOP_LOWER: "stop-lower", EXCLUSIVE: "exclusive-group" }),
    DAYS: Object.freeze([
      { id: 0, short: "Sun", name: "Sunday" },
      { id: 1, short: "Mon", name: "Monday" },
      { id: 2, short: "Tue", name: "Tuesday" },
      { id: 3, short: "Wed", name: "Wednesday" },
      { id: 4, short: "Thu", name: "Thursday" },
      { id: 5, short: "Fri", name: "Friday" },
      { id: 6, short: "Sat", name: "Saturday" }
    ]),
    ALARM_PRESETS: Object.freeze([
      { "id": "beacon", "name": "Beacon" },
      { "id": "classic", "name": "Classic Bell" },
      { "id": "pulse", "name": "Soft Pulse" },
      { "id": "chime", "name": "Warm Chime" },
      { "id": "urgent", "name": "Urgent" },
      { "id": "rapid", "name": "Rapid Alert" },
      { "id": "siren", "name": "Siren Sweep" },
      { "id": "alarmClock", "name": "Alarm Clock" },
      { "id": "critical", "name": "Critical" },
      { "id": "hammer", "name": "Hammer Pulse" },
      { "id": "sonar", "name": "Sonar" },
      { "id": "radar", "name": "Radar" },
      { "id": "flightDeck", "name": "Flight Deck" },
      { "id": "towerPing", "name": "Tower Ping" },
      { "id": "warningPulse", "name": "Warning Pulse" },
      { "id": "tripleBeep", "name": "Triple Beep" },
      { "id": "softBell", "name": "Soft Bell" },
      { "id": "deepAlert", "name": "Deep Alert" },
      { "id": "cleanPing", "name": "Clean Ping" },
      { "id": "highTone", "name": "High Tone" },
      { "id": "lowTone", "name": "Low Tone" },
      { "id": "doubleChime", "name": "Double Chime" },
      { "id": "signalSweep", "name": "Signal Sweep" },
      { "id": "warningSweep", "name": "Warning Sweep" },
      { "id": "digitalAlert", "name": "Digital Alert" },
      { "id": "attention", "name": "Attention" },
      { "id": "priority", "name": "Priority" },
      { "id": "dispatch", "name": "Dispatch" },
      { "id": "scanner", "name": "Scanner" },
      { "id": "systemReady", "name": "System Ready" },
      { "id": "notify", "name": "Notify" },
      { "id": "alertOne", "name": "Alert One" },
      { "id": "alertTwo", "name": "Alert Two" },
      { "id": "alertThree", "name": "Alert Three" },
      { "id": "system", "name": "System Notification Sound" }
    ]),
    ALARM_STOP_METHODS: Object.freeze([
      { id: "duration", name: "Auto-stop after duration" },
      { id: "controls", name: "Manual Stop controls only" },
      { id: "duration-or-controls", name: "Duration or Stop controls" },
      { id: "notification-controls", name: "Notification Stop or duration" },
      { id: "any-interaction", name: "Any interaction or duration" },
      { id: "keyboard", name: "Keyboard shortcut only" }
    ])
  });
})();
